# Required items.
game: "Far Cry Primal"
api: 1
steamID: 371660
uid: com.thegreatcabbage.farcryprimal
author: TheGreatCabbage
packageName: farcryprimal
features:
  - graphics

# Optional items.
graphicsConfig: $!DOCUMENTS!$/My Games/Far Cry Primal/gamerprofile.xml
gameDirectory: "Far Cry Primal"
verificationPaths:
  - bin/FCPrimal.exe